# @Time :2019/7/7 23:26
# @Author :jinbiao

python_exception = {"object": "对象", "iterable": "迭代", "sequence": "序列",
                    "instance": "实例", "required": "必须", "argument": "参数"}
print(python_exception["object"])
